#spring:
#  r2dbc:
#    password: 991216..tao1844631486TAO
#    username: root
#    url: r2dbc:mysql://124.222.37.186:3306
#    name: catm
#    url: ${MYSQL_DB_URL}
logging:
  level:
    org.springframework.r2dbc: debug
spring:
  r2dbc:
    password: 123456
    username: root
    url: r2dbc:mysql://127.0.0.1:3306
    name: catm
