version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    networks:
      - catm-net
    environment:
      MYSQL_DB_URL: r2dbc:mysql://root:IzO6Jqs5ncX.Nq6LrKRUKoSx@127.0.0.1:3306/catm?charset=utf8mb4
      MINIO_ENDPOINT: http://minio:9000
      MINIO_BUCKET_NAME: catm
      MINIO_ACCESS_KEY: 12345678
      MINIO_SECRET_KEY: 12345678
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.2.0
    restart: always
    networks:
      - catm-net
    environment:
      MYSQL_DATABASE: catm
      MYSQL_ROOT_PASSWORD: IzO6Jqs5ncX.Nq6LrKRUKoSx
    volumes:
      - catm-mysql-volume:/var/lib/mysql

  redis:
    image: redis
    restart: always
    networks:
      - catm-net

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - catm-net
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=12345678
    volumes:
      - catm-minio-volume:/data
    command: server /data --console-address ":9001"

volumes:
  catm-mysql-volume:
  catm-minio-volume:

networks:
  catm-net:
